# This workflow will build and push a new container image to Alibaba Cloud Container Registry (ACR),
# and then will deploy it to Alibaba Cloud Container Service for Kubernetes (ACK), when there is a push to the "master" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ACR repository to store your container images.
#    You can use ACR EE instance for more security and better performance.
#    For instructions see https://www.alibabacloud.com/help/doc-detail/142168.htm
#
# 2. Create an ACK cluster to run your containerized application.
#    You can use ACK Pro cluster for more security and better performance.
#    For instructions see https://www.alibabacloud.com/help/doc-detail/95108.htm
#
# 3. Store your AccessKey pair in GitHub Actions secrets named `ACCESS_KEY_ID` and `ACCESS_KEY_SECRET`.
#    For instructions on setting up secrets see: https://developer.github.com/actions/managing-workflows/storing-secrets/
#
# 4. Change the values for the REGION_ID, REGISTRY, NAMESPACE, IMAGE, ACK_CLUSTER_ID, and ACK_DEPLOYMENT_NAME.
#

name: Build and Deploy to ACK

on:
  push:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-chengdu
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: namespace
  IMAGE: repo
  TAG: ${{ github.sha }}
  ACK_CLUSTER_ID: clusterID
  ACK_DEPLOYMENT_NAME: nginx-deployment

  ACR_EE_REGISTRY: myregistry.cn-chengdu.cr.aliyuncs.com
  ACR_EE_INSTANCE_ID: instanceID
  ACR_EE_NAMESPACE: namespace
  ACR_EE_IMAGE: repo
  ACR_EE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1.1 Login to ACR
#      - name: Deploy to aliyun server        # 为 step 指定一个名称，将会在 github action 的控制台中显示
#        uses: easingthemes/ssh-deploy@v2.1.5      #可以访问的仓库，实现的上传服务器步骤被封装在此action
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SECRET }}  #这个是阿里云的私钥
#          ARGS: "-avzr --delete"
#          SOURCE: "./"
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}    #阿里云的 ip
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}    #阿里云用户
#          TARGET: ${{secrets.APACHE_HTML_PATH}}       #被部署的服务器路径
      - name: Deploy to aliyun server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      #2. 安装nvm
      - name: nvm action setup
        uses: actions/setup-node@v2
        with:
          node-version: "${{secrets.NODE_VERSION}}"
      #2. git
      - name: Set up Git
        run: |
          git config user.email "1364952827@qq.com"
          git config user.name "ZZL"
          git status
      #3. 构建代码 生成dist文件
      - name: Build
        run: |
          npm install
          npm run build
      #4. 转发到apache 的html目录下
      - name: Deploy
        run: |
          sudo cp -r dist/* "${{secrets.APACHE_HTML_PATH}}}"
